import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#131316",
        surface: "#131316",
        "surface-dim": "#131316",
        "surface-bright": "#39393c",
        "surface-container-lowest": "#0e0e11",
        "surface-container-low": "#1b1b1e",
        "surface-container": "#201f22",
        "surface-container-high": "#2a2a2d",
        "surface-container-highest": "#353438",
        "on-surface": "#e5e1e6",
        "on-surface-variant": "#ccc3d8",
        "inverse-surface": "#e5e1e6",
        "inverse-on-surface": "#303033",
        outline: "#958da1",
        "outline-variant": "#4a4455",
        "surface-tint": "#d2bbff",
        primary: "#d2bbff",
        "on-primary": "#3f008e",
        "primary-container": "#7c3aed",
        "on-primary-container": "#ede0ff",
        "inverse-primary": "#732ee4",
        "primary-fixed": "#eaddff",
        "primary-fixed-dim": "#d2bbff",
        "on-primary-fixed": "#25005a",
        "on-primary-fixed-variant": "#5a00c6",
        secondary: "#40efb7",
        "on-secondary": "#003827",
        "secondary-container": "#00d29c",
        "on-secondary-container": "#00543d",
        "secondary-fixed": "#54fdc4",
        "secondary-fixed-dim": "#27e0a9",
        "on-secondary-fixed": "#002116",
        "on-secondary-fixed-variant": "#00513b",
        tertiary: "#ffb95f",
        "on-tertiary": "#472a00",
        "tertiary-container": "#905b00",
        "on-tertiary-container": "#ffe1c0",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "surface-variant": "#353438",
        "on-background": "#e5e1e6",
      },
      fontFamily: {
        grotesk: ["Space Grotesk", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        jetbrains: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        "2xl": "64px",
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "spin-slow": "spin 20s linear infinite",
      },
    },
  },
  plugins: [],
};
export default config;
